easyfinance.client/src/app/Features/app-routing.module.ts, easyfinance.client/src/app/Features/income/add-income/add-income.component.ts, easyfinance.client/src/app/Features/income/list-incomes/list-incomes.component.ts, easyfinance.client/src/app/Features/project/detail-project/detail-project.component.html, easyfinance.client/src/app/Features/project/detail-project/detail-project.component.spec.ts, easyfinance.client/src/app/Features/project/detail-project/detail-project.component.ts, easyfinance.client/src/app/Features/project/list-projects/list-projects.component.ts
=> Feat: Created detail page for project

EasyFinance.Server/Program.cs, easyfinance.client/src/app/Features/project/list-projects/list-projects.component.html, easyfinance.client/src/app/Features/project/list-projects/list-projects.component.ts
Add entire button clickable
Create workaround for SENDGRID_API_KEY API so we are able to run server locally
=> Fix button clickable and API key to run server locally

easyfinance.client/cypress/e2e/user/detail-user.cy.ts, easyfinance.client/src/app/features/user/detail-user/detail-user.component.ts
Fixed bug when you try to cancel the modification of password
- Related Issue #172 
- Closes #172
=> Fix: Fixed error on cancel modify password

EasyFinance.Server/Program.cs
Change from thumbprint to file
- Closes #
=> Fix: Added file import because thumbprint didn't work on production

EasyFinance.Server/Program.cs
=> fix: Changed from hard coded to environmentvariable

EasyFinance.Application/Features/CategoryService/CategoryService.cs, easyfinance.client/src/app/core/utils/custom-validators/combo-required-validator.ts, easyfinance.client/src/app/features/category/add-category/add-category.component.html, easyfinance.client/src/app/features/category/add-category/add-category.component.ts, easyfinance.client/src/app/features/expense/add-expense-item/add-expense-item.component.html, easyfinance.client/src/app/features/expense/add-expense-item/add-expense-item.component.ts, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.html, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.ts, easyfinance.client/src/app/features/income/add-income/add-income.component.html, easyfinance.client/src/app/features/income/add-income/add-income.component.ts, easyfinance.client/src/app/features/project/add-project/add-project.component.html, easyfinance.client/src/app/features/project/add-project/add-project.component.ts
- Related Issue #192 
- Closes #192 
=> Feat: Added material to all add forms

EasyFinance.Domain/Financial/BaseFinancial.cs
Hot fix to fix the problem to add expense item on live.
- Closes #
=> Fix: Added validation to UTC to try solve the problem.

EasyFinance.Application/Contracts/Persistence/IGenericRepository.cs, EasyFinance.Persistence/Repositories/GenericRepository.cs, EasyFinance.Server/Program.cs, easyfinance.client/cypress/e2e/category/add-category.cy.ts, easyfinance.client/cypress/e2e/expense/add-expense-item.cy.ts, easyfinance.client/cypress/e2e/expense/add-expense.cy.ts, easyfinance.client/cypress/e2e/income/add-income.cy.ts, easyfinance.client/cypress/e2e/project/add-project.cy.ts, easyfinance.client/cypress/e2e/project/detail-project.cy.ts, easyfinance.client/cypress/fixtures/categories.json, easyfinance.client/cypress/fixtures/expenseItems.json, easyfinance.client/cypress/fixtures/expenses.json, easyfinance.client/cypress/fixtures/incomes.json, easyfinance.client/cypress/fixtures/projects.json, easyfinance.client/cypress/fixtures/types.ts, easyfinance.client/src/app/features/expense/add-expense-item/add-expense-item.component.ts, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.ts, easyfinance.client/src/app/features/income/add-income/add-income.component.html, easyfinance.client/src/app/features/income/add-income/add-income.component.ts
Create end to end tests to validate the principals flows from the website.
- Closes #
=> Feat: Added tests to validate Create project flow.

easyfinance.client/cypress/e2e/income/add-income.cy.ts, easyfinance.client/src/app/core/components/current-date/current-date.component.html, easyfinance.client/src/app/core/components/current-date/current-date.component.ts, easyfinance.client/src/app/core/services/category.service.ts, easyfinance.client/src/app/core/services/expense.service.ts, easyfinance.client/src/app/core/services/income.service.ts, easyfinance.client/src/app/core/utils/date/date.ts, easyfinance.client/src/app/features/app.component.ts, easyfinance.client/src/app/features/category/add-category/add-category.component.ts, easyfinance.client/src/app/features/category/list-categories/list-categories.component.html, easyfinance.client/src/app/features/category/list-categories/list-categories.component.ts, easyfinance.client/src/app/features/expense/add-expense-item/add-expense-item.component.ts, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.ts, easyfinance.client/src/app/features/expense/detail-expense/detail-expense.component.ts, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.ts, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.html, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/app/features/income/add-income/add-income.component.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.html, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts
Resolved some small bugs with date.
- Related Issue #207 #208 #209
- Closes #207 #208 #209
=> Fix: bug with dates, bug validation error, bug on datepicker

easyfinance.client/cypress/e2e/expense/list-expenses.cy.ts, easyfinance.client/cypress/fixtures/types.ts, easyfinance.client/src/app/features/category/list-categories/list-categories.component.ts, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.ts, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.html, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts
Fixed bug when you update some expense item the list wasn't updated and fixed another bug that make modify date impossible.
- Related Issue #213 
- Closes #213 
=> Fix: update item after save and date change.

easyfinance.client/cypress/e2e/income/list-incomes.cy.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.html, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts
Fixed bug when you try to edit income amount with decimal numbers
- Related Issue #210 
- Closes #210 
=> Fix: bug when you try edit amount with decimal

easyfinance.client/src/app/core/components/current-date/current-date.component.css, easyfinance.client/src/app/features/category/list-categories/list-categories.component.css, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.css, easyfinance.client/src/app/features/project/detail-project/detail-project.component.css, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/styles.css
Modified to keep a pattern in the date selector.
- Related Issue #225
- Closes #225 
=> Feat: Modified to keep a pattern in the date selector.

easyfinance.client/src/app/core/components/add-button/add-button.component.html, easyfinance.client/src/app/core/components/return-button/return-button.component.html, easyfinance.client/src/styles.css
Modified add button.
- Related Issue #226 
- Closes #226 
=> Feat: Modified add button.

EasyFinance.Application/Features/ExpenseService/ExpenseService.cs, EasyFinance.Persistence/PersistenceServiceRegistration.cs, EasyFinance.Server/Controllers/ExpensesController.cs
Modified to search and fill the user in the expenseItem
- Related Issue #108 
- Closes #108 
=> Fix: Duplicated users on database.

EasyFinance.Application/Features/ExpenseService/ExpenseService.cs
Fix to solve the problem that create a new user every time that a expense is updated or a expense item is created.
- Related Issue #108 
- Closes #108 
=> feat: Fixed to track changes and don't create new users.

easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.html, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/styles.css
Feature
This PR introduces Angular material for edit form.
Resolved #217
=> feat(#217): Changed edit forms to use angular material

.github/CONTRIBUTING.md, EasyFinance.Common.Tests/AccessControl/UserBuilder.cs, EasyFinance.Domain.Tests/AccessControl/UserTests.cs, EasyFinance.Domain/AccessControl/User.cs, EasyFinance.Infrastructure/ValidationMessages.resx, EasyFinance.Infrastructure/Validators/CurrencyValidator.cs, EasyFinance.Infrastructure/Validators/TimeZoneValidator.cs, EasyFinance.Persistence/Mapping/AccessControl/UserConfiguration.cs, EasyFinance.Persistence/Migrations/20241112145427_AddedCurrencyAndTimezone.Designer.cs, EasyFinance.Persistence/Migrations/20241112145427_AddedCurrencyAndTimezone.cs, EasyFinance.Persistence/Migrations/EasyFinanceDatabaseContextModelSnapshot.cs, EasyFinance.Server/Controllers/AccountController.cs, EasyFinance.Server/DTOs/AccessControl/UserRequestDTO.cs, EasyFinance.Server/DTOs/AccessControl/UserResponseDTO.cs, EasyFinance.Server/Program.cs, easyfinance.client/cypress/e2e/auth/register.cy.ts, easyfinance.client/cypress/fixtures/types.ts, easyfinance.client/cypress/fixtures/users.json
Created properties PreferredCurrency and Timezone in User and exposed to edit and return when get user.
- Related Issue #233 #240 
- Closes #233 #240 
=> Feat/#233 #240 add new fields to user model

easyfinance.client/src/app/core/pipes/currency-format.pipe.spec.ts, easyfinance.client/src/app/core/pipes/currency-format.pipe.ts
Created currency formatting pipe and unit test
Related to #243
=> feat(#243): Create currency formatting pipe

easyfinance.client/cypress/e2e/auth/register.cy.ts, easyfinance.client/cypress/e2e/user/detail-user.cy.ts, easyfinance.client/cypress/fixtures/types.ts, easyfinance.client/cypress/fixtures/users.json, easyfinance.client/src/app/core/pipes/currency-format.pipe.spec.ts, easyfinance.client/src/app/core/services/currency.service.ts, easyfinance.client/src/app/core/services/user.service.ts, easyfinance.client/src/app/features/authentication/first-sign-in/first-sign-in.component.css, easyfinance.client/src/app/features/authentication/first-sign-in/first-sign-in.component.html, easyfinance.client/src/app/features/authentication/first-sign-in/first-sign-in.component.ts, easyfinance.client/src/app/features/user/detail-user/detail-user.component.css, easyfinance.client/src/app/features/user/detail-user/detail-user.component.html, easyfinance.client/src/app/features/user/detail-user/detail-user.component.ts
Added possibility to configure preferred currency to first-sign-in and user page.
- Related Issue #242 
- Closes #242
=> Feat: Added preferred currency to first-sign-in and user page.

easyfinance.client/cypress/e2e/income/list-incomes.cy.ts, easyfinance.client/src/app/features/app.component.ts, easyfinance.client/src/app/features/category/list-categories/list-categories.component.html, easyfinance.client/src/app/features/category/list-categories/list-categories.component.ts, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.html, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.ts, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.html, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.ts, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.html, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.html, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts, easyfinance.client/src/main.ts
Applied currencyFormat in all places.
- Related Issue #244 
- Closes #244 
=> Feat: Applied currencyFormat in all places.

.github/CONTRIBUTING.md
- Related Issue #262
- Closes #262
=> feat: Add prerequisites to CONTRIBUTING.md file

EasyFinance.Domain/Financial/BaseFinancial.cs, easyfinance.client/cypress/e2e/income/list-incomes.cy.ts, easyfinance.client/src/app/features/authentication/login/login.component.html, easyfinance.client/src/app/features/authentication/login/login.component.ts, easyfinance.client/src/app/features/authentication/register/register.component.html, easyfinance.client/src/app/features/authentication/register/register.component.ts, easyfinance.client/src/app/features/category/list-categories/list-categories.component.html, easyfinance.client/src/app/features/category/list-categories/list-categories.component.ts, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.html, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.ts, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.html, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts, easyfinance.client/src/app/features/project/list-projects/list-projects.component.html, easyfinance.client/src/app/features/project/list-projects/list-projects.component.ts
- Related Issue #239
- Closes #239
=> 239 frontend apply angular material in edit forms

easyfinance.client/src/app/features/authentication/register/register.component.html
- Related Issue #265 
- Closes #265 
=> fix: fix sign up button and error messages in register page (#265)

EasyFinance.Common.Tests/AccessControl/UserBuilder.cs, EasyFinance.Domain/AccessControl/User.cs, EasyFinance.Infrastructure/ValidationMessages.resx, EasyFinance.Server.Tests/Controllers/AccountControllerTests.cs, EasyFinance.Server.Tests/EasyFinance.Server.Tests.csproj, EasyFinance.Server/Controllers/AccountController.cs, EasyFinance.Server/DTOs/AccessControl/UserSearchResponseDTO.cs
- Related Issue #268
- Closes #268
=> 268 backend search users endpoint

easyfinance.client/cypress/e2e/expense/add-expense-item.cy.ts, easyfinance.client/cypress/e2e/expense/add-expense.cy.ts, easyfinance.client/cypress/e2e/expense/list-expense-items.cy.ts, easyfinance.client/cypress/e2e/expense/list-expenses.cy.ts, easyfinance.client/cypress/e2e/income/add-income.cy.ts, easyfinance.client/cypress/e2e/income/list-incomes.cy.ts, easyfinance.client/package-lock.json, easyfinance.client/package.json, easyfinance.client/src/app/features/expense/add-expense-item/add-expense-item.component.html, easyfinance.client/src/app/features/expense/add-expense-item/add-expense-item.component.ts, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.html, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.ts, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.html, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.ts, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.html, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/app/features/income/add-income/add-income.component.html, easyfinance.client/src/app/features/income/add-income/add-income.component.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.html, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts
This DRAFT PR introduces a currency mask feature to enhance user convenience while entering or inputting currency values.
+ Integrated currency masks using ng2-currency-mask.
+ Refactored the code to handle decimals and thousand separators automatically through global configuration, ensuring a seamless user experience.
+ UI Enhancements: Addressing the issue of currency symbols appearing twice—once from the ng2-currency-mask and again as a static tag value. This will be resolved in the final PR.
+ Testing: Additional testing may be required in some areas to ensure full functionality.
=> feat-220-Adding mask to amount fields

EasyFinance.Application.Tests/UserServiceTests.cs, EasyFinance.Application/ApplicationServiceRegistration.cs, EasyFinance.Application/EasyFinance.Application.csproj, EasyFinance.Application/Features/ProjectService/IProjectService.cs, EasyFinance.Application/Features/ProjectService/ProjectService.cs, EasyFinance.Application/Features/UserService/IUserService.cs, EasyFinance.Application/Features/UserService/UserSerivce.cs, EasyFinance.Infrastructure/ValidationMessages.resx, EasyFinance.Server.Tests/Controllers/AccountControllerTests.cs, EasyFinance.Server/Controllers/AccountController.cs, EasyFinance.Server/DTOs/AccessControl/UserDeleteRequestDTO.cs
Change the user delete logic to be token-based confirmation.
- Related Issue #277 
- Closes #277 
=> Feat: changed delete user to be token-based confirmation

EasyFinance.Application/Features/UserService/UserSerivce.cs, EasyFinance.Infrastructure/Exceptions/ValidationException.cs, EasyFinance.Infrastructure/ValidationMessages.resx, EasyFinance.Server/Controllers/AccountController.cs
Modified wrong status code when return error.
- Closes #
=> Fix: Error when token is invalid.

EasyFinance.Application/Features/ProjectService/ProjectService.cs
Deleted dependencies to avoid error.
- Closes #
=> Fix: removed dependencies to be possible delete user

EasyFinance.Server/Config/EmailSender.cs
Created cool email layout and applied this for all emails.
- Related Issue #283
- Closes #283
=> feat-backend-283-create-design-for-emails

easyfinance.client/src/app/features/authentication/login/login.component.html, easyfinance.client/src/app/features/authentication/register/register.component.html
=> #291 - Changed input placeholder from "Passsword" to Password

easyfinance.client/cypress/e2e/user/detail-user.cy.ts, easyfinance.client/cypress/fixtures/users.json, easyfinance.client/src/app/features/user/detail-user/detail-user.component.html, easyfinance.client/src/app/features/user/detail-user/detail-user.component.ts
Fix error when user click on cancel and the user is deleted anyway.
- Related Issue #295 
- Closes #295 
=> fix: Error when try cancel delete

easyfinance.client/cypress/e2e/project/detail-project.cy.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts
Added validation to show the button for the user just when it's relevant.
- Related Issue #304 
- Closes #304 
=> Feat: Should consider the previous month before show the button

EasyFinance.Server/Controllers/ProjectsController.cs, easyfinance.client/src/app/features/category/list-categories/list-categories.component.html, easyfinance.client/src/app/features/category/list-categories/list-categories.component.ts, easyfinance.client/src/app/features/category/models/category-dto.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts, easyfinance.client/src/app/features/project/models/year-expenses-summary-dto.ts
Added more information in the dashboard to be more visible that you already overspend in some category even if you don't do that in the total value.
- Related Issue #306 
- Closes #306 
=> Feat: Added overspend info in the project detail and list categories

easyfinance.client/cypress/e2e/user/detail-user.cy.ts, easyfinance.client/src/app/features/user/detail-user/detail-user.component.html, easyfinance.client/src/app/features/user/detail-user/detail-user.component.ts
- Modified user detail interface to allow editing at all times
- Removed conditional rendering that restricted edit functionality
- Updated design to show editable fields consistently
- Fixed the layout of the password save button and modified to use material.
- Verified user can edit details at any time
- Tested form validation still works correctly
- Confirmed changes persist in database
- Related Issue #302 
- Closes #302
=> Updating detail-user component so all fields are shown

.github/workflows/Release.yml, EasyFinance.Application.Tests/EasyFinance.Application.Tests.csproj, EasyFinance.Application.Tests/UserServiceTests.cs, EasyFinance.Application/EasyFinance.Application.csproj, EasyFinance.Common.Tests/EasyFinance.Common.Tests.csproj, EasyFinance.Domain.Tests/EasyFinance.Domain.Tests.csproj, EasyFinance.Domain/EasyFinance.Domain.csproj, EasyFinance.Infrastructure/EasyFinance.Infrastructure.csproj, EasyFinance.Persistence/EasyFinance.Persistence.csproj, EasyFinance.Server.Tests/Controllers/AccountControllerTests.cs, EasyFinance.Server.Tests/EasyFinance.Server.Tests.csproj, EasyFinance.Server/EasyFinance.Server.csproj, easyfinance.client/easyfinance.client.esproj, easyfinance.client/src/app/features/authentication/recovery/recovery.component.ts, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts, easyfinance.client/src/app/features/project/list-projects/list-projects.component.ts
Updated all dependencies
- Related Issue #325 
- Closes #325 
=> Feat: Updated all dependencies and fixed new deploy folder in front end

.github/workflows/Release.yml
Fix release pipeline
- Closes #
=> fix: release pipeline

.devcontainer/devcontainer.json, .github/CONTRIBUTING.md, .github/dependabot.yml, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html
Fixed the amount showed for the client.
- Related Issue #328 
- Closes #328 
=> Fixed the amount showed.

easyfinance.client/cypress/e2e/user/detail-user.cy.ts, easyfinance.client/src/app/core/components/confirm-dialog/confirm-dialog.component.html, easyfinance.client/src/app/core/components/confirm-dialog/confirm-dialog.component.ts, easyfinance.client/src/app/features/user/detail-user/detail-user.component.html, easyfinance.client/src/app/features/user/detail-user/detail-user.component.ts
Added confirmation message when change currency.
- Related Issue #255 
- Closes #255 
=> Feat: Added confirmation message when change currency.

EasyFinance.Persistence/Migrations/20250129202058_AddedDefaultProjectToUser.cs
Fix error on migration
- Closes #
=> Fix error on migration

easyfinance.client/src/app/core/components/nav-bar/nav-bar.component.css, easyfinance.client/src/app/core/components/nav-bar/nav-bar.component.html, easyfinance.client/src/app/core/components/nav-bar/nav-bar.component.ts
Added button to show the menu on mobile.
- Related Issue #340 
- Closes #340 
=> Fix: Added button to show the menu on mobile.

easyfinance.client/src/app/core/interceptor/loading.interceptor.ts, easyfinance.client/src/app/core/services/auth.service.ts, easyfinance.client/src/app/features/app.component.ts
Created polling logic to avoid outdated user configs
- Related Issue #342 
- Closes #342 
=> Feat: Created polling logic to avoid outdated user configs

easyfinance.client/src/app/core/components/nav-bar/nav-bar.component.html, easyfinance.client/src/app/core/services/auth.service.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts, easyfinance.client/src/app/features/project/list-projects/list-projects.component.css, easyfinance.client/src/app/features/project/list-projects/list-projects.component.html, easyfinance.client/src/app/features/project/list-projects/list-projects.component.ts
Fix some stuffs and add some minor changes to improve experience.
- Closes #
=> Feat: fix and change some minor changes

EasyFinance.Application/Features/AccessControlService/AccessControlService.cs, EasyFinance.Application/Features/AccessControlService/IAccessControlService.cs, EasyFinance.Domain.Tests/AccessControl/UserProjectTests.cs, EasyFinance.Domain/AccessControl/UserProject.cs, EasyFinance.Infrastructure/ValidationMessages.resx, EasyFinance.Server.Tests/Controllers/AccountControllerTests.cs, EasyFinance.Server/Controllers/AccountController.cs, EasyFinance.Server/Controllers/BaseController.cs, EasyFinance.Server/Controllers/ProjectsController.cs, EasyFinance.Server/Program.cs, easyfinance.client/src/app/core/components/accept-invite/accept-invite.component.ts, easyfinance.client/src/app/core/guards/auth-guard.ts, easyfinance.client/src/app/core/services/auth.service.ts, easyfinance.client/src/app/core/services/project.service.ts, easyfinance.client/src/app/features/app-routing.module.ts, easyfinance.client/src/app/features/authentication/login/login.component.ts, easyfinance.client/src/app/features/authentication/register/register.component.ts
Modified back and front end to be possible accept the invitation.
- Related Issue #271 
- Closes #271 
=> Feat: Modified back and front end to be possible accept the invitation.

easyfinance.client/package-lock.json, easyfinance.client/package.json, easyfinance.client/src/app/features/app.component.ts, easyfinance.client/src/app/features/authentication/register/register.component.ts, easyfinance.client/src/canvas-confetti.d.ts
Added confettis when user finish his registration
- Related Issue #346 
- Closes #346 
=> Feat: Added confettis when user finish his registration

easyfinance.client/src/main.ts
Fix bug calendar that not open on dialog
- Related Issue #359 
- Closes #359 
=> Fix bug calendar that not open on dialog

EasyFinance.Application/DTOs/AccessControl/UserResponseDTO.cs, EasyFinance.Application/DTOs/AccessControl/UserSearchResponseDTO.cs, EasyFinance.Application/Features/AccessControlService/AccessControlService.cs, EasyFinance.Application/Features/AccessControlService/IAccessControlService.cs, EasyFinance.Application/Mappers/UserMap.cs, EasyFinance.Application/Mappers/UserProjectMap.cs, EasyFinance.Server.Tests/Controllers/AccountControllerTests.cs, EasyFinance.Server/Controllers/AccountController.cs, easyfinance.client/src/app/core/models/user.ts, easyfinance.client/src/app/core/services/user.service.ts, easyfinance.client/src/app/features/project/access-control-project/access-control-project.component.html, easyfinance.client/src/app/features/project/access-control-project/access-control-project.component.ts
Changed to just show already know user to avoid user has information from other users.
- Related Issue #357 
- Closes #357 
=> Feat: Changed to just show already know user.

EasyFinance.Application/Features/ProjectService/IProjectService.cs, EasyFinance.Application/Features/ProjectService/ProjectService.cs, EasyFinance.Server/Controllers/ProjectsController.cs, EasyFinance.Server/Program.cs, easyfinance.client/cypress/e2e/project/add-project.cy.ts, easyfinance.client/cypress/fixtures/types.ts, easyfinance.client/src/app/core/components/nav-bar/nav-bar.component.ts, easyfinance.client/src/app/core/enums/Role.ts, easyfinance.client/src/app/core/guards/auth-guard.ts, easyfinance.client/src/app/core/interceptor/http-request-interceptor.ts, easyfinance.client/src/app/core/models/user-project.ts, easyfinance.client/src/app/core/services/error-message.service.ts, easyfinance.client/src/app/core/services/global.service.ts, easyfinance.client/src/app/core/services/project.service.ts, easyfinance.client/src/app/core/utils/pipes/currency-format.pipe.spec.ts, easyfinance.client/src/app/core/utils/pipes/currency-format.pipe.ts, easyfinance.client/src/app/features/category/list-categories/list-categories.component.html, easyfinance.client/src/app/features/category/list-categories/list-categories.component.ts, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.html, easyfinance.client/src/app/features/expense/list-expense-items/list-expense-items.component.ts, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.html, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.html, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts, easyfinance.client/src/app/features/project/list-projects/list-projects.component.html, easyfinance.client/src/app/features/project/list-projects/list-projects.component.ts, easyfinance.client/src/app/features/project/models/user-project-dto.ts
looked all pages and change to show and hide edit buttons based on users permissions
- Related Issue #356 #355 
- Closes #356 #355 
=> look all pages and change to show and hide edit buttons based on users permissions

.github/workflows/BuildAndTests.yml, .github/workflows/Release.yml, easyfinance.client/package-lock.json
Added node_modules to cache to make the pipeline faster.
- Related Issue #363 
- Closes #363 
=> Feat: Added node_modules to cache to make the pipeline faster.

easyfinance.client/src/app/core/utils/pipes/currency-format.pipe.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts
- Changed name from `Incomes` to `Total Income`.
- Changed color from green to black to avoid misunderstand.
- Removed decimals from the overview screen to improve clarity.
- Closes #
=> Fix: Small changes to improve usability

EasyFinance.Application/DTOs/AccessControl/TokenRequestDTO.cs, EasyFinance.Application/DTOs/AccessControl/TokenResponseDTO.cs, EasyFinance.Common.Tests/BaseTests.cs, EasyFinance.Infrastructure/Authentication/TokenSettings.cs, EasyFinance.Server.Tests/Config/TokenUtilTests.cs, EasyFinance.Server.Tests/Controllers/AccountControllerTests.cs, EasyFinance.Server/Config/EmailSender.cs, EasyFinance.Server/Config/TokenUtil.cs, EasyFinance.Server/Controllers/AccountController.cs, EasyFinance.Server/EasyFinance.Server.csproj, EasyFinance.Server/MiddleWare/AuthenticationMiddleware.cs, EasyFinance.Server/MiddleWare/AuthorizationMiddleware.cs, EasyFinance.Server/Program.cs, EasyFinance.Server/appsettings.json, easyfinance.client/cypress/support/commands.ts, easyfinance.client/src/app/core/interceptor/http-request-interceptor.ts, easyfinance.client/src/app/core/models/token.ts, easyfinance.client/src/app/core/services/auth.service.ts, easyfinance.client/src/app/core/services/local.service.ts, easyfinance.client/src/app/core/services/project.service.ts, easyfinance.client/src/app/core/services/user.service.ts, easyfinance.client/src/app/core/utils/json-parser.ts, easyfinance.client/src/app/core/utils/pipes/currency-format.pipe.ts, easyfinance.client/src/app/features/authentication/logout/logout.component.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html
Changed project authentication to be token based
- Related Issue #373 
- Closes #373 
=> Changed project authentication to be token based

.github/workflows/BuildAndTests.yml, .github/workflows/Release.yml
fix: pipeline cache
- Closes #
=> fix: pipeline cache

EasyFinance.Application/Features/AccessControlService/AccessControlService.cs, easyfinance.client/src/app/core/components/accept-invite/accept-invite.component.ts
Fixed error when try manage user
- Closes #
=> Fix: Fixed error when try manage user

easyfinance.client/src/app/core/services/category.service.ts
Bug to load expensees on january
- Related Issue #402 
- Closes #402 
=> Fix bug on january

.github/CONTRIBUTING.md, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.html, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts, easyfinance.client/src/assets/i18n/messages.en.json, easyfinance.client/src/assets/i18n/messages.pt.json
Redesign the list of income
- Related Issue #414 
- Closes #414 
=> Feat: Redesign the list of income

easyfinance.client/src/app/core/enums/subscription-level.ts, easyfinance.client/src/app/features/project/add-edit-project/add-edit-project.component.ts
company projects not available for user with access
- Closes #
=> Fix: function not available

EasyFinance.Application/Features/ProjectService/ProjectService.cs, easyfinance.client/src/app/core/services/project.service.ts
Reset date and latests transactions error.
- Related Issue #428 
- Closes #428 
=> Fix: Reset date and latests transactions error.

EasyFinance.Application/Features/ProjectService/ProjectService.cs
Fix: Improved latest search
- Closes #
=> Fix: Improved latest search

EasyFinance.Application/Features/ProjectService/ProjectService.cs
Fix production error when try execute query in SQL Server.
- Closes #
=> Fix production error when try execute query in SQL Server.

.github/CONTRIBUTING.md, .github/workflows/BuildAndTests.yml, EasyFinance.Application/Contracts/Persistence/IUnitOfWork.cs, EasyFinance.Application/DTOs/FinancialProject/ClientRequestDTO.cs, EasyFinance.Application/DTOs/FinancialProject/ClientResponseDTO.cs, EasyFinance.Application/DTOs/FinancialProject/ProjectResponseDTO.cs, EasyFinance.Application/Features/ClientService/ClientService.cs, EasyFinance.Application/Features/ClientService/IClientService.cs, EasyFinance.Application/Features/ProjectService/ProjectService.cs, EasyFinance.Application/Mappers/ClientMap.cs, EasyFinance.Domain/FinancialProject/Client.cs, EasyFinance.Domain/FinancialProject/Project.cs, EasyFinance.Infrastructure/ValidationMessages.pt.resx, EasyFinance.Infrastructure/ValidationMessages.resx, EasyFinance.Persistence/DatabaseContext/EasyFinanceDatabaseContext.cs, EasyFinance.Persistence/Mapping/FinancialProject/ClientConfiguration.cs, EasyFinance.Persistence/Mapping/FinancialProject/ProjectConfiguration.cs, EasyFinance.Persistence/Repositories/UnitOfWork.cs, EasyFinance.Server.Tests/AuthorizationMiddlewareTests.cs, EasyFinance.Server/Controllers/ClientController.cs, EasyFinance.Server/MiddleWare/AuthorizationMiddleware.cs
Created CRUD backend for client
- Related Issue #406 #434 
- Closes #406 #434 
=> Created CRUD backend for client

EasyFinance.Application/Features/CategoryService/CategoryService.cs
=> Fix error when show total in overview

EasyFinance.Application/Features/UserService/UserSerivce.cs
Fixed error when try to delete account that has default project.
- Closes #
=> Fix error when try to delete account with default project

EasyFinance.Infrastructure/ValidationMessages.pt.resx, EasyFinance.Infrastructure/ValidationMessages.resx, easyfinance.client/src/app/features/app-routing.module.ts, easyfinance.client/src/app/features/not-authenticated-area/how-to/how-to.component.html, easyfinance.client/src/app/features/not-authenticated-area/how-to/how-to.component.ts, easyfinance.client/src/assets/i18n/messages.en.json, easyfinance.client/src/assets/i18n/messages.pt.json
=> Fix default category names

easyfinance.client/src/app/core/components/current-date/current-date.component.ts, easyfinance.client/src/app/core/services/category.service.ts, easyfinance.client/src/app/core/services/expense.service.ts, easyfinance.client/src/app/core/services/income.service.ts, easyfinance.client/src/app/core/utils/date.ts, easyfinance.client/src/app/features/expense/add-expense-item/add-expense-item.component.ts, easyfinance.client/src/app/features/expense/add-expense/add-expense.component.ts, easyfinance.client/src/app/features/expense/expense-item/expense-item.component.ts, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/app/features/income/add-income/add-income.component.ts, easyfinance.client/src/app/features/income/list-incomes/list-incomes.component.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.ts
Fix: Error with timezone in countries with negative hour.
- Related Issue #445 
- Closes #445 
=> Fix: Error with timezone in countries with negative hour.

EasyFinance.Server/MiddleWare/LocalizationMiddleware.cs, EasyFinance.Server/Program.cs, easyfinance.client/src/app/core/interceptor/http-request-interceptor.ts
- Fix to avoid many calls to refresh token.
- Removed unecessary logs.
- Related Issue #437 
- Closes #437 
=> Fix: Avoid many calls to refresh token

EasyFinance.Domain.Tests/Financial/ExpenseTests.cs, EasyFinance.Domain/Financial/BaseExpense.cs, EasyFinance.Domain/Financial/BaseFinancial.cs, EasyFinance.Domain/Financial/Income.cs
Add possibility to exempt specific error messages defined at a lower level when considering if an app response is considered Succeeded/Failed when checking Validate.
- Related Issue 
- Closes https://github.com/FelipePSoares/EconoFlow/issues/451
=> Fixes #451

EasyFinance.Domain.Tests/Financial/ExpenseItemTests.cs, EasyFinance.Domain.Tests/Financial/ExpenseTests.cs, EasyFinance.Domain.Tests/Financial/IncomeTests.cs, EasyFinance.Domain/Financial/BaseExpense.cs, EasyFinance.Domain/Financial/Income.cs, EasyFinance.Infrastructure/ValidationMessages.pt.resx, EasyFinance.Infrastructure/ValidationMessages.resx, EasyFinance.Server/Controllers/CategoriesController.cs, EasyFinance.Server/Controllers/ClientsController.cs, EasyFinance.Server/Controllers/IncomesController.cs, EasyFinance.Server/Controllers/ProjectsController.cs, EasyFinance.Server/Controllers/SupportController.cs, easyfinance.client/cypress/e2e/expense/list-expenses.cy.ts, easyfinance.client/src/app/features/expense/add-expense-item/add-expense-item.component.ts
Error when some validation return an error or when it's an expense item error.
- Related Issue #456 #454 
- Closes #456 #454
=> Fix: Error when some validation return an error or when it's an expense item error.

easyfinance.client/src/app/core/components/nav-bar/nav-bar.component.html, easyfinance.client/src/app/core/components/nav-bar/nav-bar.component.ts
logo link when no project is selected
- Closes #
=> Fix: logo link when no project is selected

easyfinance.client/src/app/features/project/detail-project/detail-project.component.html
Added color green and red to be easier to understand
- Closes #
=> Feat: Added color green and red to be easier to understand

EasyFinance.Server/Program.cs
Change from Certificate to DPAPI encrypt to prevent error when has certificate rotation.
- Closes #
=> Feat: Change from Certificate to DPAPI encrypt

easyfinance.client/src/app/core/interceptor/http-request-interceptor.ts
Error when try refresh token after sometime away
- Related Issue #485 
- Closes #485 
=> Fix: error when try refresh token after sometime away

EasyFinance.Application/DTOs/Financial/CategoryResponseDTO.cs, EasyFinance.Application/Features/CategoryService/CategoryService.cs, EasyFinance.Application/Mappers/CategoryMap.cs, easyfinance.client/cypress/e2e/category/add-category.cy.ts, easyfinance.client/src/app/core/models/category.ts, easyfinance.client/src/app/features/category/models/category-dto.ts, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.css, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.html, easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.ts, easyfinance.client/src/app/features/project/detail-project/detail-project.component.css, easyfinance.client/src/app/features/project/detail-project/detail-project.component.html, easyfinance.client/src/assets/i18n/messages.en.json, easyfinance.client/src/assets/i18n/messages.pt.json
Added effect grayed on the categories that was archived
- Related Issue #487 
- Closes #487 
=> Feat: Added effect grayed on the categories that was archived

EasyFinance.Server/Program.cs
Added hsts to the website to increase safety.
- Related Issue #449 
=> Added hsts to the website to increase safety.

EasyFinance.Server/EasyFinance.Server.http, EasyFinance.Server/MiddleWare/SecurityPolicyMiddleware.cs, EasyFinance.Server/Program.cs, easyfinance.client/src/app/app.config.ts
Added CSP nonce.
- Related Issue #449 
=> Feat: Added CSP nonce.

EasyFinance.Server/MiddleWare/SecurityPolicyMiddleware.cs, easyfinance.client/src/app/app.config.ts, easyfinance.client/src/index.html
Added nonce to meta tag
- Related Issue #449 
=> Feat: Added nonce to meta tag

easyfinance.client/src/app/core/interceptor/loading.interceptor.ts, easyfinance.client/src/app/core/services/version-check.service.ts, easyfinance.client/src/app/features/app.component.ts, easyfinance.client/src/assets/version.json
Added check version logic.
- Related Issue #483 
- Closes #483 
=> Feat: Added check version logic.

EasyFinance.Application/DTOs/AccessControl/UserRequestDTO.cs, EasyFinance.Application/DTOs/AccessControl/UserResponseDTO.cs, EasyFinance.Application/Mappers/UserMap.cs, EasyFinance.Domain/AccessControl/NotificationChannels.cs, EasyFinance.Domain/AccessControl/User.cs, EasyFinance.Persistence/Mapping/AccessControl/UserConfiguration.cs, EasyFinance.Persistence/Migrations/20250905083028_AddNotificationChannelsProperty.Designer.cs, EasyFinance.Persistence/Migrations/20250905083028_AddNotificationChannelsProperty.cs, EasyFinance.Server/Config/FlagsEnumArrayConverter.cs, EasyFinance.Server/Controllers/AccountController.cs, EasyFinance.Server/Controllers/CategoriesController.cs, EasyFinance.Server/EmailTemplates/en/TermsAndPolicyChanged.html, EasyFinance.Server/Program.cs, easyfinance.client/src/app/features/not-authenticated-area/privacy-policy/privacy-policy.component.html, easyfinance.client/src/app/features/not-authenticated-area/use-terms/use-terms.component.html
backend notification preferences with enum flags
- Related Issue #502 
- Closes #502 
=> backend notification preferences with enum flags

easyfinance.client/src/app/core/utils/loaders/translate-http-loader.ts, easyfinance.client/src/app/features/user/account/account.component.ts, easyfinance.client/src/app/features/user/emails/emails.component.ts, easyfinance.client/src/assets/version.json
Fix problem with new translations
- Closes #
=> Feat: Fix problem with new translations

easyfinance.client/angular.json, easyfinance.client/src/index.html, easyfinance.client/src/robots.txt, easyfinance.client/src/sitemap.xml
Added SEO stuffs
- Related Issue #450 
- Closes #450 
=> Feat: Added SEO stuffs

easyfinance.client/src/robots.txt
=> Improve robot.txt
